version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./backend.dockerfile
    container_name: pita-backend
    ports:
      - '8000:8000'
    volumes:
      - .:/home/PITA
