# Generated by Django 3.1.7 on 2021-04-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('vpn', models.IntegerField()),
                ('hostgroup', models.CharField(max_length=256)),
                ('nagios_ip', models.CharField(max_length=16)),
            ],
        ),
    ]
